FROM python:3.8
ENV PYTHONUNBUFFERED 1


ARG DJANGO_ALLOWED_HOSTS
ARG DJANGO_SECRET_KEY

ENV DJANGO_ALLOWED_HOSTS ${DJANGO_ALLOWED_HOSTS}
ENV DJANGO_SECRET_KEY ${DJANGO_SECRET_KEY}

RUN mkdir /backend
WORKDIR /backend

ADD . /backend/

RUN pip install -r requrements.txt