# Generated by Django 3.1.3 on 2020-11-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquran',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surat', models.IntegerField(default=0)),
                ('ayat', models.IntegerField(default=0)),
                ('arab', models.TextField()),
                ('indonesia', models.TextField()),
            ],
        ),
    ]
